"""
Tests for the admin-portal Fees and Transport modules added by the QA audit
close-out: academic years, fee categories, fee structures, assignments,
concessions, ledger, reports, payments and the transport sub-modules
(drivers, attendants, pickup points, passes, trips, alerts, settings,
reports, live map).

The raw portal tables live only in the production/CI schema (applied by
``apply_portal_schema``), so every test class creates the tables it needs
with vendor-portable DDL and fakes ``table_exists`` for the whole class.
JWT bearer auth is used, matching the SIMPLE_JWT configuration.

Run with:
    python manage.py test portal.tests.test_fees_transport
"""
from datetime import date, timedelta
from unittest import mock

from django.contrib.auth import get_user_model
from django.db import connection
from django.test import TestCase
from django.utils.timezone import now
from rest_framework_simplejwt.tokens import RefreshToken

import portal.admin_views as admin_views
import portal.roles as portal_roles

User = get_user_model()

VENDOR = connection.vendor
IS_SQLITE = VENDOR == "sqlite"

if IS_SQLITE:
    # The view layer composes SQL with psycopg2.sql (Composed objects), which
    # only the Postgres driver accepts natively. Django's sqlite backend
    # stringifies placeholders itself, so coerce composed queries to their
    # plain-text form before the driver sees them. Identifiers reach only
    # whitelisted/constant names, so no quoting is needed here.
    from psycopg2 import sql as pysql_sql
    from django.db.backends.sqlite3.base import SQLiteCursorWrapper

    def _render_composed(query):
        if isinstance(query, str):
            return query
        parts = []
        for part in query:
            if isinstance(part, pysql_sql.Composed):
                parts.append(_render_composed(part))
            elif isinstance(part, (pysql_sql.SQL, pysql_sql.Placeholder)):
                parts.append(part.as_string(None))
            elif isinstance(part, pysql_sql.Identifier):
                parts.append(".".join(part._wrapped))
            else:
                raise TypeError(f"Unsupported psycopg2.sql part: {type(part).__name__}")
        text = "".join(parts)
        # SimpleTableView paints omitted columns with the DEFAULT keyword,
        # which Postgres understands but SQLite does not; NULL is the safe
        # portable equivalent because test DDL never requires the default.
        if "DEFAULT" in text:
            text = text.replace("DEFAULT", "NULL")
        return text

    _orig_sqlite_execute = SQLiteCursorWrapper.execute

    def _sqlite_composed_execute(self, query, params=None):
        return _orig_sqlite_execute(self, _render_composed(query), params)

    SQLiteCursorWrapper.execute = _sqlite_composed_execute


def _pk():
    return "INTEGER PRIMARY KEY AUTOINCREMENT" if IS_SQLITE else "integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"


def _ref(table):
    # Plain integers: tests rely on UNIQUE constraints (not FK integrity).
    return "INTEGER"


def _types():
    if IS_SQLITE:
        return {"bool": "INTEGER", "num": "NUMERIC", "date": "TEXT", "ts": "TEXT", "time": "TEXT", "str": "TEXT"}
    return {"bool": "boolean", "num": "numeric", "date": "date", "ts": "timestamptz", "time": "time", "str": "text"}


T = _types()


def _unique(name):
    return f"CONSTRAINT {name} UNIQUE" if not IS_SQLITE else "UNIQUE"


TABLES = [
    # Portal core tables referenced by the fee/transport joins.
    f"""
    CREATE TABLE IF NOT EXISTS portal_class (
      id {_pk()},
      name varchar(100),
      section varchar(20)
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_user_profile (
      user_id {_pk()},
      user_type varchar(30),
      phone_number varchar(30)
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_student_profile (
      user_id {_pk()},
      parent_id {_ref("auth_user")},
      admission_number varchar(50),
      date_of_birth {T['date']},
      gender varchar(10),
      status varchar(20)
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_student_enrollment (
      id {_pk()},
      student_id {_ref("auth_user")} NOT NULL,
      class_id {_ref("portal_class")},
      academic_year varchar(20),
      roll_number integer
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_vehicle (
      id {_pk()},
      vehicle_number varchar(50),
      capacity integer,
      driver_id {_ref("auth_user")},
      gps_device_id varchar(80),
      maintenance_status varchar(30)
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_route (
      id {_pk()},
      route_name varchar(100),
      start_point varchar(100),
      end_point varchar(100),
      vehicle_id {_ref("portal_vehicle")},
      attendant_id {_ref("portal_attendant")}
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_transport_allocation (
      id {_pk()},
      student_id {_ref("auth_user")} NOT NULL {_unique("uniq_allocation_student")},
      vehicle_id {_ref("portal_vehicle")} NOT NULL,
      route_id {_ref("portal_route")} NOT NULL,
      pickup_point varchar(200)
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_academic_year (
      id {_pk()},
      name varchar(100) {_unique("uniq_academic_year_name")} NOT NULL,
      start_date {T['date']} NOT NULL,
      end_date {T['date']} NOT NULL,
      is_active {T['bool']} DEFAULT false
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_fee_category (
      id {_pk()},
      name varchar(100) {_unique("uniq_fee_category_name")} NOT NULL,
      description {T['str']},
      sort_order integer DEFAULT 99,
      is_active {T['bool']} DEFAULT true
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_fee_structure (
      id {_pk()},
      class_id {_ref("portal_class")} NOT NULL,
      term_name varchar(60) NOT NULL,
      academic_year_id {_ref("portal_academic_year")},
      due_date {T['date']},
      late_fine_per_day {T['num']} DEFAULT 0,
      tuition_fee {T['num']} DEFAULT 0,
      admission_fee {T['num']} DEFAULT 0,
      transport_fee {T['num']} DEFAULT 0,
      hostel_fee {T['num']} DEFAULT 0,
      library_fee {T['num']} DEFAULT 0,
      exam_fee {T['num']} DEFAULT 0,
      misc_fee {T['num']} DEFAULT 0,
      description {T['str']},
      is_published {T['bool']} DEFAULT false,
      total_amount {T['num']} DEFAULT 0
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_payment (
      id {_pk()},
      student_id {_ref("auth_user")} NOT NULL,
      fee_structure_id {_ref("portal_fee_structure")} NOT NULL,
      transaction_id varchar(80),
      amount_paid {T['num']} NOT NULL,
      payment_method varchar(30),
      status varchar(20) NOT NULL,
      paid_at {T['ts']} NOT NULL
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_fee_assignment (
      id {_pk()},
      fee_structure_id {_ref("portal_fee_structure")} NOT NULL,
      student_id {_ref("auth_user")} NOT NULL,
      assigned_at {T['ts']} DEFAULT CURRENT_TIMESTAMP,
      {_unique("uniq_assignment")} (fee_structure_id, student_id)
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_fee_concession (
      id {_pk()},
      student_id {_ref("auth_user")} NOT NULL,
      fee_structure_id {_ref("portal_fee_structure")} NOT NULL,
      concession_type varchar(60) DEFAULT 'Scholarship',
      discount_amount {T['num']} DEFAULT 0,
      discount_percent {T['num']} DEFAULT 0,
      reason {T['str']},
      CHECK (discount_amount >= 0),
      CHECK (discount_amount = 0 OR discount_percent = 0),
      CHECK (discount_percent >= 0 AND discount_percent <= 100)
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_driver (
      id {_pk()},
      user_id {_ref("auth_user")} NOT NULL {_unique("uniq_driver_user")},
      license_number varchar(100),
      phone varchar(30),
      vehicle_id {_ref("portal_vehicle")},
      is_active {T['bool']} DEFAULT true
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_attendant (
      id {_pk()},
      user_id {_ref("auth_user")} NOT NULL {_unique("uniq_attendant_user")},
      phone varchar(30),
      assigned_route_id {_ref("portal_route")},
      is_active {T['bool']} DEFAULT true
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_pickup_point (
      id {_pk()},
      route_id {_ref("portal_route")} NOT NULL,
      name varchar(200) NOT NULL,
      sequence_order integer DEFAULT 1,
      pickup_time {T['time']},
      drop_time {T['time']}
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_transport_pass (
      id {_pk()},
      student_id {_ref("auth_user")} NOT NULL {_unique("uniq_pass_student")},
      pass_number varchar(40) {_unique("uniq_pass_number")} NOT NULL,
      issued_at {T['ts']} DEFAULT CURRENT_TIMESTAMP
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_transport_trip (
      id {_pk()},
      vehicle_id {_ref("portal_vehicle")} NOT NULL,
      route_id {_ref("portal_route")},
      trip_date {T['date']} DEFAULT CURRENT_DATE,
      status varchar(30) DEFAULT 'Scheduled',
      started_at {T['ts']},
      ended_at {T['ts']}
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_transport_alert (
      id {_pk()},
      type varchar(30) NOT NULL,
      message {T['str']} NOT NULL,
      vehicle_id {_ref("portal_vehicle")},
      route_id {_ref("portal_route")},
      created_by {_ref("auth_user")},
      created_at {T['ts']} DEFAULT CURRENT_TIMESTAMP
    )""",
    f"""
    CREATE TABLE IF NOT EXISTS portal_transport_settings (
      id integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
      contact_number varchar(30),
      annual_transport_fee {T['num']} DEFAULT 0,
      fee_due_date {T['date']},
      gps_update_interval_sec integer DEFAULT 30
    )""",
]

# Tables created by the migrations on both vendors (never dropped).
CORE = {"auth_user"}


class PortalTablesTestCase(TestCase):
    """Creates the raw portal tables for the class and fakes table_exists."""

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls._created = set(TABLES_NAMED)
        with connection.cursor() as cursor:
            for ddl in TABLES:
                cursor.execute(ddl)
        cls._patch = mock.patch.object(
            admin_views, "table_exists",
            side_effect=lambda name: name in cls._created or name in CORE,
        )
        cls._patch.start()
        cls.addClassCleanup(cls._patch.stop)
        # roles.table_exists queries information_schema (Postgres-only), so the
        # audit-log helper must be told the log table is absent on sqlite too.
        cls._roles_patch = mock.patch.object(
            portal_roles, "_table_exists", side_effect=lambda name: False,
        )
        cls._roles_patch.start()
        cls.addClassCleanup(cls._roles_patch.stop)

    def _admin(self):
        user = User.objects.create_superuser(username="boss", email="boss@edunova.edu", password="BossPass@99")
        return user

    def _auth(self, user):
        token = RefreshToken.for_user(user).access_token
        return {"HTTP_AUTHORIZATION": f"Bearer {token}"}

    def _make_student(self, username, admission_number=None, class_id=None):
        user = User.objects.create_user(username=username, email=f"{username}@edunova.edu", password="Pass@1234",
                                        first_name=username)
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_user_profile (user_id, user_type, phone_number) VALUES (%s, %s, %s)",
                [user.id, "Student", "9000000000"],
            )
            cursor.execute(
                "INSERT INTO portal_student_profile (user_id, admission_number, gender, status) "
                "VALUES (%s, %s, 'Male', 'Active')",
                [user.id, admission_number or f"ADM-{user.id:04d}"],
            )
            if class_id:
                cursor.execute(
                    "INSERT INTO portal_student_enrollment (student_id, class_id, academic_year, roll_number) "
                    "VALUES (%s, %s, '2025-26', %s)",
                    [user.id, class_id, user.id],
                )
        return user

    def _make_class(self, name="Class 5", section="A"):
        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO portal_class (name, section) VALUES (%s, %s) RETURNING id", [name, section])
            return cursor.fetchone()[0]

    def _make_fee_structure(self, class_id, term="Term 1", total=1000.0,
                            due_date=None, fine=0.0, academic_year_id=None):
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_fee_structure (class_id, term_name, academic_year_id, due_date, "
                "late_fine_per_day, tuition_fee, total_amount, is_published) "
                "VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING id",
                [class_id, term, academic_year_id, due_date, fine, total, total, True],
            )
            return cursor.fetchone()[0]

    def _make_vehicle(self, number="KA-01-1234"):
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_vehicle (vehicle_number, capacity, maintenance_status) "
                "VALUES (%s, %s, 'Operational') RETURNING id",
                [number, 40],
            )
            return cursor.fetchone()[0]

    def _make_route(self, name="Route 1"):
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_route (route_name, start_point, end_point) "
                "VALUES (%s, %s, %s) RETURNING id",
                [name, "Start Point", "End Point"],
            )
            return cursor.fetchone()[0]


TABLES_NAMED = []


def _collect_table_names():
    for ddl in TABLES:
        for line in ddl.strip().splitlines():
            s = line.strip()
            if s.startswith("CREATE TABLE IF NOT EXISTS "):
                TABLES_NAMED.append(s.replace("CREATE TABLE IF NOT EXISTS ", "").strip().split()[0])


_collect_table_names()


class AcademicYearTests(PortalTablesTestCase):
    URL = "/api/admin-portal/academic-years/"

    def test_create_and_single_active(self):
        admin = self._admin()
        auth = self._auth(admin)
        resp = self.client.post(self.URL, {
            "name": "2026-27", "start_date": "2026-04-01", "end_date": "2027-03-31", "is_active": True,
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        year_id = resp.json()["id"]

        resp = self.client.post(self.URL, {
            "name": "2025-26", "start_date": "2025-04-01", "end_date": "2026-03-31", "is_active": True,
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        second_id = resp.json()["id"]

        resp = self.client.get(self.URL, **auth)
        self.assertEqual(resp.status_code, 200)
        by_id = {r["id"]: r for r in resp.json()}
        self.assertEqual(by_id[year_id]["is_active"], 0 if IS_SQLITE else False)
        self.assertEqual(by_id[second_id]["is_active"], 1 if IS_SQLITE else True)

    def test_name_required_and_date_order(self):
        auth = self._auth(self._admin())
        resp = self.client.post(self.URL, {"start_date": "2026-04-01", "end_date": "2027-03-31"},
                                content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)
        resp = self.client.post(self.URL, {
            "name": "Bad", "start_date": "2027-04-01", "end_date": "2026-03-31",
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)
        self.assertIn("end date", resp.json()["detail"])


class FeeCategoryTests(PortalTablesTestCase):
    URL = "/api/admin-portal/fee-categories/"

    def test_crud(self):
        auth = self._auth(self._admin())
        resp = self.client.post(self.URL, {"name": "Tuition", "sort_order": 1}, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        cat_id = resp.json()["id"]

        resp = self.client.get(self.URL, **auth)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.json()[0]["name"], "Tuition")

        resp = self.client.patch(self.URL, {"id": cat_id, "description": "Core tuition fee"},
                                 content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 200)

        resp = self.client.delete(f"{self.URL}?id={cat_id}", **auth)
        self.assertEqual(resp.status_code, 200)
        resp = self.client.delete(f"{self.URL}?id={cat_id}", **auth)
        self.assertEqual(resp.status_code, 404)


class FeeStructureTests(PortalTablesTestCase):
    URL = "/api/admin-portal/fee-structures/"

    def setUp(self):
        super().setUp()
        self.class_id = self._make_class()

    def test_total_computed_from_components(self):
        auth = self._auth(self._admin())
        resp = self.client.post(self.URL, {
            "class_id": self.class_id, "term_name": "Term 1",
            "tuition_fee": 5000, "admission_fee": 500, "transport_fee": 1000,
            "hostel_fee": 0, "library_fee": 200, "exam_fee": 300, "misc_fee": 0,
            "due_date": (date.today() + timedelta(days=30)).isoformat(),
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        with connection.cursor() as cursor:
            cursor.execute("SELECT total_amount FROM portal_fee_structure WHERE class_id = %s", [self.class_id])
            self.assertEqual(float(cursor.fetchone()[0]), 7000.0)

    def test_bad_components_and_past_due_date(self):
        auth = self._auth(self._admin())
        resp = self.client.post(self.URL, {
            "class_id": self.class_id, "term_name": "T1", "tuition_fee": "abc",
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)
        resp = self.client.post(self.URL, {
            "class_id": self.class_id, "term_name": "T1", "tuition_fee": 100,
            "due_date": str(date.today() - timedelta(days=1)),
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)
        self.assertIn("due date", resp.json()["detail"])

    def test_list_joins_class_and_collected(self):
        structure_id = self._make_fee_structure(self.class_id, total=1000.0)
        student = self._make_student("s1", class_id=self.class_id)
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_payment (student_id, fee_structure_id, transaction_id, amount_paid, "
                "payment_method, status, paid_at) VALUES (%s, %s, %s, %s, %s, %s, %s)",
                [student.id, structure_id, "TXN1", 500, "Cash", "Success", now()],
            )
        resp = self.client.get(self.URL, **self._auth(self._admin()))
        self.assertEqual(resp.status_code, 200)
        row = resp.json()[0]
        self.assertEqual(row["class_name"], "Class 5-A")
        self.assertEqual(float(row["amount_collected"]), 500.0)


class FeeAssignmentTests(PortalTablesTestCase):
    URL = "/api/admin-portal/fee-assignments/"

    def setUp(self):
        super().setUp()
        self.class_id = self._make_class()

    def test_single_assign_list_delete(self):
        auth = self._auth(self._admin())
        student = self._make_student("s1", class_id=self.class_id)
        structure_id = self._make_fee_structure(self.class_id)
        self._make_student("s2", class_id=self.class_id)

        resp = self.client.post(self.URL, {"fee_structure_id": structure_id, "student_id": student.id},
                                content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        assign_id = resp.json()["id"]

        resp = self.client.get(self.URL, {"fee_structure_id": structure_id}, **auth)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual([r["student_id"] for r in resp.json()], [student.id])
        self.assertEqual(resp.json()[0]["student_name"].strip(), "s1")

        # The second student is not assigned; deleting that id 404s.
        resp = self.client.delete(f"{self.URL}?id={assign_id + 1}", **auth)
        self.assertEqual(resp.status_code, 404)

        resp = self.client.delete(f"{self.URL}?id={assign_id}", **auth)
        self.assertEqual(resp.status_code, 200)

    def test_bulk_assign_class(self):
        auth = self._auth(self._admin())
        self._make_student("s1", class_id=self.class_id)
        self._make_student("s2", class_id=self.class_id)
        structure_id = self._make_fee_structure(self.class_id)

        resp = self.client.post(self.URL, {"fee_structure_id": structure_id, "assign_class": True},
                                content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.json()["count"], 2)

        # Re-running must be idempotent.
        resp = self.client.post(self.URL, {"fee_structure_id": structure_id, "assign_class": True},
                                content_type="application/json", **auth)
        self.assertEqual(resp.json()["count"], 0)

        # A student not enrolled in the class stays unassigned.
        s3 = self._make_student("s3")
        resp = self.client.get(self.URL, {"fee_structure_id": structure_id}, **auth)
        self.assertNotIn(s3.id, [r["student_id"] for r in resp.json()])

    def test_required_params(self):
        auth = self._auth(self._admin())
        resp = self.client.get(self.URL, **auth)
        self.assertEqual(resp.status_code, 400)
        resp = self.client.post(self.URL, {"student_id": 1}, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)


class FeeConcessionTests(PortalTablesTestCase):
    URL = "/api/admin-portal/fee-concessions/"

    def setUp(self):
        super().setUp()
        self.class_id = self._make_class()
        self.structure_id = self._make_fee_structure(self.class_id, total=1000.0)

    def test_create_validate_list_delete(self):
        auth = self._auth(self._admin())
        student = self._make_student("s1", class_id=self.class_id)

        resp = self.client.post(self.URL, {
            "student_id": student.id, "fee_structure_id": self.structure_id,
            "concession_type": "Merit", "discount_amount": 200,
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        concession_id = resp.json()["id"]

        # Amount and percent together violate the CHECK constraint.
        resp = self.client.post(self.URL, {
            "student_id": student.id, "fee_structure_id": self.structure_id,
            "discount_amount": 100, "discount_percent": 10,
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)

        resp = self.client.post(self.URL, {
            "student_id": student.id, "fee_structure_id": self.structure_id, "discount_percent": 110,
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)

        resp = self.client.post(self.URL, {
            "student_id": student.id, "fee_structure_id": self.structure_id, "concession_type": "Nope",
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)

        resp = self.client.get(self.URL, **auth)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.json()[0]["concession_type"], "Merit")
        self.assertEqual(float(resp.json()[0]["discount_amount"]), 200.0)

        resp = self.client.delete(f"{self.URL}?id={concession_id}", **auth)
        self.assertEqual(resp.status_code, 200)


class FeeLedgerTests(PortalTablesTestCase):
    URL = "/api/admin-portal/fee-ledger/"

    def setUp(self):
        super().setUp()
        self.class_id = self._make_class()

    def test_ledger_statuses(self):
        auth = self._auth(self._admin())
        due_future = str(date.today() + timedelta(days=30))
        structure_id = self._make_fee_structure(self.class_id, total=1000.0, due_date=due_future, fine=10.0)
        s1 = self._make_student("unpaid", class_id=self.class_id)
        s2 = self._make_student("partial", class_id=self.class_id)
        s3 = self._make_student("paid", class_id=self.class_id)
        for student in (s1, s2, s3):
            with connection.cursor() as cursor:
                cursor.execute(
                    "INSERT INTO portal_fee_assignment (fee_structure_id, student_id) VALUES (%s, %s)",
                    [structure_id, student.id],
                )
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_payment (student_id, fee_structure_id, transaction_id, amount_paid, "
                "payment_method, status, paid_at) VALUES (%s, %s, %s, %s, %s, %s, %s)",
                [s2.id, structure_id, "T1", 400, "Cash", "Success", now()],
            )
            cursor.execute(
                "INSERT INTO portal_payment (student_id, fee_structure_id, transaction_id, amount_paid, "
                "payment_method, status, paid_at) VALUES (%s, %s, %s, %s, %s, %s, %s)",
                [s3.id, structure_id, "T2", 1000, "UPI", "Success", now()],
            )

        resp = self.client.get(self.URL, {"fee_structure_id": structure_id}, **auth)
        self.assertEqual(resp.status_code, 200)
        ledger = {r["student_name"].strip(): r for r in resp.json()}
        self.assertEqual(ledger["unpaid"]["status"], "Unpaid")
        self.assertEqual(float(ledger["unpaid"]["balance_due"]), 1000.0)
        self.assertEqual(ledger["partial"]["status"], "Partial")
        self.assertEqual(float(ledger["partial"]["balance_due"]), 600.0)
        self.assertEqual(ledger["paid"]["status"], "Paid")
        self.assertEqual(float(ledger["paid"]["balance_due"]), 0.0)

    def test_overdue_and_concession(self):
        auth = self._auth(self._admin())
        due_past = str(date.today() - timedelta(days=5))
        structure_id = self._make_fee_structure(self.class_id, total=1000.0, due_date=due_past, fine=10.0)
        student = self._make_student("s1", class_id=self.class_id)
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_fee_assignment (fee_structure_id, student_id) VALUES (%s, %s)",
                [structure_id, student.id],
            )
            cursor.execute(
                "INSERT INTO portal_fee_concession (student_id, fee_structure_id, concession_type, "
                "discount_percent) VALUES (%s, %s, 'Merit', %s)",
                [student.id, structure_id, 10],
            )
        resp = self.client.get(self.URL, {"fee_structure_id": structure_id}, **auth)
        self.assertEqual(resp.status_code, 200)
        row = resp.json()[0]
        self.assertEqual(row["status"], "Overdue")
        # 1000 gross - 10% concession = 900 net; 5 overdue days x 10 = 50 fine; nothing paid.
        self.assertEqual(float(row["concession_amount"]), 100.0)
        self.assertEqual(float(row["net_payable"]), 900.0)
        self.assertEqual(float(row["fine_amount"]), 50.0)
        self.assertEqual(float(row["balance_due"]), 950.0)

    def test_validation(self):
        auth = self._auth(self._admin())
        resp = self.client.get(self.URL, **auth)
        self.assertEqual(resp.status_code, 400)
        resp = self.client.post(self.URL, {}, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)
        resp = self.client.get(self.URL, {"fee_structure_id": 999}, **auth)
        self.assertEqual(resp.status_code, 404)
        structure_id = self._make_fee_structure(self.class_id, total=100.0)
        resp = self.client.post(self.URL, {"fee_structure_id": structure_id},
                                content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.json()["detail"], "Ledger generated.")


class FeeReportsTests(PortalTablesTestCase):
    URL = "/api/admin-portal/fee-reports/"

    def setUp(self):
        super().setUp()
        self.class_id = self._make_class()

    def test_summary_structure_monthly_pending(self):
        auth = self._auth(self._admin())
        due_future = str(date.today() + timedelta(days=10))
        structure_id = self._make_fee_structure(self.class_id, total=1000.0, due_date=due_future)
        student = self._make_student("s1", class_id=self.class_id)
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_fee_assignment (fee_structure_id, student_id) VALUES (%s, %s)",
                [structure_id, student.id],
            )
            cursor.execute(
                "INSERT INTO portal_payment (student_id, fee_structure_id, transaction_id, amount_paid, "
                "payment_method, status, paid_at) VALUES (%s, %s, %s, %s, %s, %s, %s)",
                [student.id, structure_id, "TXN-1", 250, "Cash", "Success", now()],
            )

        resp = self.client.get(self.URL, **auth)
        self.assertEqual(resp.status_code, 200)
        body = resp.json()
        self.assertEqual(float(body["summary"]["total_collected"]), 250.0)
        self.assertEqual(body["summary"]["unique_payers"], 1)
        self.assertEqual(len(body["monthly"]), 12)
        self.assertEqual(body["structures"][0]["class_name"], "Class 5-A")
        self.assertEqual(float(body["structures"][0]["amount_collected"]), 250.0)
        self.assertIn({"status": "Partial", "count": 1, "total_balance": 750.0},
                      [{"status": p["status"], "count": p["count"], "total_balance": float(p["total_balance"])}
                       for p in body["pending"]])

    def test_unknown_year_returns_no_structures(self):
        auth = self._auth(self._admin())
        structure_id = self._make_fee_structure(self.class_id, total=1000.0)
        student = self._make_student("s1", class_id=self.class_id)
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_payment (student_id, fee_structure_id, transaction_id, amount_paid, "
                "payment_method, status, paid_at) VALUES (%s, %s, %s, %s, %s, %s, %s)",
                [student.id, structure_id, "TXN-2", 500, "UPI", "Success", now()],
            )
        resp = self.client.get(self.URL, {"academic_year_id": 999}, **auth)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.json()["structures"], [])


class PaymentListViewTests(PortalTablesTestCase):
    URL = "/api/admin-portal/payments/"

    def test_list_joins_student_and_term(self):
        auth = self._auth(self._admin())
        class_id = self._make_class()
        structure_id = self._make_fee_structure(class_id, total=1000.0)
        student = self._make_student("s1", class_id=class_id)
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_payment (student_id, fee_structure_id, transaction_id, amount_paid, "
                "payment_method, status, paid_at) VALUES (%s, %s, %s, %s, 'Cash', 'Success', %s)",
                [student.id, structure_id, "TXN-9", 1000, now()],
            )
        resp = self.client.get(self.URL, **auth)
        self.assertEqual(resp.status_code, 200)
        row = resp.json()[0]
        self.assertEqual(row["transaction_id"], "TXN-9")
        self.assertEqual(row["student_name"].strip(), "s1")
        self.assertEqual(row["admission_number"], f"ADM-{student.id:04d}")
        self.assertEqual(row["class_name"], "Class 5")
        self.assertEqual(row["section"], "A")
        self.assertEqual(row["term_name"], "Term 1")


class VehicleRouteTests(PortalTablesTestCase):
    def test_vehicle_create_with_text_gps_and_join(self):
        auth = self._auth(self._admin())
        driver_user = User.objects.create_user(username="driver1", password="Pass@1234", first_name="driver1")
        resp = self.client.post("/api/admin-portal/vehicles/", {
            "vehicle_number": "KA-01-5678", "capacity": 36, "driver_id": driver_user.id,
            "gps_device_id": "GPS-XYZ-123", "maintenance_status": "Operational",
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_driver (user_id, license_number, phone, vehicle_id) "
                "VALUES (%s, %s, %s, %s)",
                [driver_user.id, "DL-1234", "9876543210", resp.json()["id"]],
            )
        resp = self.client.get("/api/admin-portal/vehicles/", **auth)
        self.assertEqual(resp.status_code, 200)
        row = resp.json()[0]
        self.assertEqual(row["driver_name"].strip(), "driver1")
        self.assertEqual(row["gps_device_id"], "GPS-XYZ-123")

    def test_route_create_with_assignments_and_stop_count(self):
        auth = self._auth(self._admin())
        vehicle_id = self._make_vehicle()
        resp = self.client.post("/api/admin-portal/routes/", {
            "route_name": "Route 7", "start_point": "A", "end_point": "B",
            "vehicle_id": vehicle_id,
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        route_id = resp.json()["id"]
        with connection.cursor() as cursor:
            for i in (1, 2, 3):
                cursor.execute(
                    "INSERT INTO portal_pickup_point (route_id, name, sequence_order) VALUES (%s, %s, %s)",
                    [route_id, f"Stop {i}", i],
                )
        resp = self.client.get("/api/admin-portal/routes/", **auth)
        self.assertEqual(resp.status_code, 200)
        row = resp.json()[0]
        self.assertEqual(row["vehicle_number"], "KA-01-1234")
        self.assertEqual(row["stop_count"], 3)

    def test_route_bad_int_column(self):
        auth = self._auth(self._admin())
        resp = self.client.post("/api/admin-portal/routes/", {
            "route_name": "R", "vehicle_id": "not-a-number",
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)


class TransportAllocationTests(PortalTablesTestCase):
    URL = "/api/admin-portal/transport-allocations/"

    def setUp(self):
        super().setUp()
        self.vehicle_id = self._make_vehicle()
        self.route_id = self._make_route()

    def test_create_list_delete_by_student(self):
        auth = self._auth(self._admin())
        student = self._make_student("s1")
        resp = self.client.post(self.URL, {
            "student_id": student.id, "vehicle_id": self.vehicle_id, "route_id": self.route_id,
            "pickup_point": "Main Gate",
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)

        resp = self.client.get(self.URL, **auth)
        self.assertEqual(resp.status_code, 200)
        row = resp.json()[0]
        self.assertEqual(row["student_name"].strip(), "s1")
        self.assertEqual(row["vehicle_number"], "KA-01-1234")
        self.assertEqual(row["route_name"], "Route 1")

        # One allocation per student is enforced by the unique constraint.
        resp = self.client.post(self.URL, {
            "student_id": student.id, "vehicle_id": self.vehicle_id, "route_id": self.route_id,
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)

        resp = self.client.delete(f"{self.URL}?student_id={student.id}", **auth)
        self.assertEqual(resp.status_code, 200)
        resp = self.client.get(self.URL, **auth)
        self.assertEqual(resp.json(), [])

    def test_delete_by_id_and_404(self):
        auth = self._auth(self._admin())
        student = self._make_student("s2")
        resp = self.client.post(self.URL, {
            "student_id": student.id, "vehicle_id": self.vehicle_id, "route_id": self.route_id,
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        alloc_id = resp.json()["id"]

        resp = self.client.delete(f"{self.URL}?id={alloc_id}", **auth)
        self.assertEqual(resp.status_code, 200)
        resp = self.client.delete(f"{self.URL}?id={alloc_id}", **auth)
        self.assertEqual(resp.status_code, 404)
        resp = self.client.delete(self.URL, **auth)
        self.assertEqual(resp.status_code, 400)


class DriverAttendantTests(PortalTablesTestCase):
    def test_driver_view(self):
        auth = self._auth(self._admin())
        user = User.objects.create_user(username="d1", password="Pass@1234", first_name="d1")
        resp = self.client.post("/api/admin-portal/transport/drivers/", {
            "user_id": user.id, "license_number": "DL-99", "phone": "1111111111",
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        resp = self.client.get("/api/admin-portal/transport/drivers/", **auth)
        self.assertEqual(resp.json()[0]["name"].strip(), "d1")

    def test_attendant_view(self):
        auth = self._auth(self._admin())
        user = User.objects.create_user(username="a1", password="Pass@1234", first_name="a1")
        resp = self.client.post("/api/admin-portal/transport/attendants/", {
            "user_id": user.id, "phone": "2222222222",
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        resp = self.client.get("/api/admin-portal/transport/attendants/", **auth)
        self.assertEqual(resp.json()[0]["name"].strip(), "a1")


class PickupPointTests(PortalTablesTestCase):
    URL = "/api/admin-portal/transport/pickup-points/"

    def test_create_filter_and_order(self):
        auth = self._auth(self._admin())
        route1 = self._make_route("Route 1")
        route2 = self._make_route("Route 2")
        resp = self.client.post(self.URL, {
            "route_id": route1, "name": "Stop B", "sequence_order": 2, "pickup_time": "07:30:00",
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        resp = self.client.post(self.URL, {
            "route_id": route1, "name": "Stop A", "sequence_order": 1,
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        resp = self.client.post(self.URL, {
            "route_id": route2, "name": "Other", "sequence_order": 1,
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)

        resp = self.client.get(self.URL, {"route_id": route1}, **auth)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual([p["name"] for p in resp.json()], ["Stop A", "Stop B"])

        resp = self.client.get(self.URL, **auth)
        self.assertEqual(len(resp.json()), 3)


class TransportPassTests(PortalTablesTestCase):
    URL = "/api/admin-portal/transport/passes/"

    def test_generate_is_idempotent(self):
        auth = self._auth(self._admin())
        vehicle_id = self._make_vehicle()
        route_id = self._make_route()
        student = self._make_student("s1")
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_transport_allocation (student_id, vehicle_id, route_id, pickup_point) "
                "VALUES (%s, %s, %s, %s)",
                [student.id, vehicle_id, route_id, "Main Gate"],
            )

        resp = self.client.post(self.URL, {"student_id": student.id}, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        pass_number = resp.json()["pass_number"]
        self.assertTrue(pass_number.startswith(f"EP-{date.today().year}-"))
        self.assertEqual(resp.json()["route_name"], "Route 1")

        resp = self.client.post(self.URL, {"student_id": student.id}, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.json()["pass_number"], pass_number)

        resp = self.client.get(self.URL, **auth)
        self.assertEqual(len(resp.json()), 1)

    def test_requires_student_id(self):
        auth = self._auth(self._admin())
        resp = self.client.post(self.URL, {}, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)


class TransportTripTests(PortalTablesTestCase):
    URL = "/api/admin-portal/transport/trips/"

    def setUp(self):
        super().setUp()
        self.vehicle_id = self._make_vehicle()
        self.route_id = self._make_route()

    def test_lifecycle_transitions(self):
        auth = self._auth(self._admin())
        resp = self.client.post(self.URL, {"vehicle_id": self.vehicle_id, "route_id": self.route_id},
                                content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        trip_id = resp.json()["id"]

        resp = self.client.get(self.URL, {"date": date.today().isoformat()}, **auth)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.json()[0]["status"], "Scheduled")

        resp = self.client.patch(self.URL, {"id": trip_id, "status": "In Progress"},
                                 content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 200)
        with connection.cursor() as cursor:
            cursor.execute("SELECT started_at FROM portal_transport_trip WHERE id = %s", [trip_id])
            self.assertIsNotNone(cursor.fetchone()[0])

        resp = self.client.patch(self.URL, {"id": trip_id, "status": "Completed"},
                                 content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 200)

    def test_invalid_transitions(self):
        auth = self._auth(self._admin())
        resp = self.client.post(self.URL, {"vehicle_id": self.vehicle_id},
                                content_type="application/json", **auth)
        trip_id = resp.json()["id"]

        resp = self.client.patch(self.URL, {"id": trip_id, "status": "Completed"},
                                 content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)
        self.assertIn("Invalid transition", resp.json()["detail"])

        resp = self.client.patch(self.URL, {"id": 999, "status": "In Progress"},
                                 content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 404)

    def test_requires_vehicle(self):
        auth = self._auth(self._admin())
        resp = self.client.post(self.URL, {}, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)


class TransportAlertTests(PortalTablesTestCase):
    URL = "/api/admin-portal/transport/notifications/"

    def test_create_and_list(self):
        auth = self._auth(self._admin())
        route_id = self._make_route()
        resp = self.client.post(self.URL, {
            "type": "Delay Alert", "message": "Bus 1 is delayed by 15 minutes", "route_id": route_id,
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)

        resp = self.client.post(self.URL, {"message": "No type"}, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 201)
        self.assertEqual(resp.json()["detail"], "Alert broadcast sent.")

        resp = self.client.post(self.URL, {"type": "Nope", "message": "x"}, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)

        resp = self.client.post(self.URL, {"type": "Info", "message": "  "}, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)

        resp = self.client.get(self.URL, **auth)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(len(resp.json()), 2)


class TransportSettingsTests(PortalTablesTestCase):
    URL = "/api/admin-portal/transport/settings/"

    def test_get_and_upsert(self):
        auth = self._auth(self._admin())
        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO portal_transport_settings (id) SELECT 1 WHERE NOT EXISTS "
                           "(SELECT 1 FROM portal_transport_settings WHERE id = 1)")
        resp = self.client.get(self.URL, **auth)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(float(resp.json()["annual_transport_fee"]), 0.0)

        resp = self.client.post(self.URL, {
            "contact_number": "080-12345678", "annual_transport_fee": 12000,
            "gps_update_interval_sec": 15,
        }, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.json()["contact_number"], "080-12345678")
        self.assertEqual(float(resp.json()["annual_transport_fee"]), 12000.0)
        self.assertEqual(resp.json()["gps_update_interval_sec"], 15)

        resp = self.client.post(self.URL, {"annual_transport_fee": 12500},
                                content_type="application/json", **auth)
        self.assertEqual(float(resp.json()["annual_transport_fee"]), 12500.0)

    def test_invalid_and_empty(self):
        auth = self._auth(self._admin())
        resp = self.client.post(self.URL, {"gps_update_interval_sec": -3}, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)
        resp = self.client.post(self.URL, {"annual_transport_fee": "abc"}, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)
        resp = self.client.post(self.URL, {}, content_type="application/json", **auth)
        self.assertEqual(resp.status_code, 400)


class TransportReportsAndLiveMapTests(PortalTablesTestCase):
    def test_reports_and_live_map(self):
        auth = self._auth(self._admin())
        vehicle_id = self._make_vehicle()
        route_id = self._make_route()
        student = self._make_student("s1")
        with connection.cursor() as cursor:
            cursor.execute(
                "INSERT INTO portal_transport_allocation (student_id, vehicle_id, route_id) VALUES (%s, %s, %s)",
                [student.id, vehicle_id, route_id],
            )
            cursor.execute(
                "INSERT INTO portal_transport_pass (student_id, pass_number) VALUES (%s, %s)",
                [student.id, "EP-2026-AB12CD34"],
            )
            cursor.execute(
                "INSERT INTO portal_transport_trip (vehicle_id, route_id, status) VALUES (%s, %s, 'Scheduled')",
                [vehicle_id, route_id],
            )

        resp = self.client.get("/api/admin-portal/transport/reports/", **auth)
        self.assertEqual(resp.status_code, 200)
        body = resp.json()
        self.assertEqual(body["total_vehicles"], 1)
        self.assertEqual(body["total_routes"], 1)
        self.assertEqual(body["allocated_students"], 1)
        self.assertEqual(body["active_passes"], 1)
        self.assertEqual(body["route_utilisation"][0]["route_name"], "Route 1")
        self.assertEqual(body["route_utilisation"][0]["student_count"], 1)
        self.assertEqual(len(body["recent_trips"]), 1)

        resp = self.client.get("/api/admin-portal/transport/live-map/", **auth)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.json()[0]["vehicle_number"], "KA-01-1234")


class AuthGuardTests(PortalTablesTestCase):
    def test_admin_only(self):
        resp = self.client.get("/api/admin-portal/fee-reports/")
        self.assertIn(resp.status_code, (401, 403))

    def test_student_forbidden(self):
        student = self._make_student("s1")
        auth = self._auth(student)
        resp = self.client.get("/api/admin-portal/fee-reports/", **auth)
        self.assertEqual(resp.status_code, 403)


class UserListTypeAliasTests(PortalTablesTestCase):
    def test_type_alias_filters_students(self):
        auth = self._auth(self._admin())
        self._make_student("stu1")
        resp = self.client.get("/api/admin-portal/users/?type=Student", **auth)
        self.assertEqual(resp.status_code, 200)
        names = [r["name"] for r in resp.json()]
        self.assertIn("stu1", names)
        self.assertNotIn("boss", names)
        self.assertEqual(resp.json()[0]["first_name"], "stu1")



