# Generated by Django 5.2.16 on 2026-08-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_campus_options_alter_cmspage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faculty/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('qualification_detail', models.CharField(blank=True, max_length=300)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('specializations', models.CharField(blank=True, help_text='Comma-separated list, e.g. Physics, Robotics, AI', max_length=500)),
                ('achievements', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'first_name'],
            },
        ),
    ]
