# Generated by Django 5.2.16 on 2026-08-09 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_facultymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusVisitBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_id', models.CharField(blank=True, max_length=50)),
                ('visitor_name', models.CharField(max_length=150)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_phone', models.CharField(max_length=20)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('visit_time', models.CharField(blank=True, max_length=30)),
                ('purpose', models.TextField(blank=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='careers/resumes/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job_posting', models.ForeignKey(db_column='job_posting_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='cms.jobposting')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
