# Generated by Django 5.2.16 on 2026-08-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_campusvisitbooking_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campus',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campus',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='campus',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='office_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campus',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='campus',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='campus',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campus',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='campus',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
