# Generated by Django 5.2.16 on 2026-08-09 07:41
#
# NOTE: admissions_open / admissions_academic_year / admissions_close_date
# already exist in the shared production DB (added out-of-band, not via a
# tracked migration). AddField state operations keep Django's model state in
# sync, while the database operation introspects existing columns and only
# issues ALTER TABLE for the ones that are missing — portable across Postgres
# (production) and SQLite (unit tests).
from django.db import connection, migrations, models


def _add_missing_columns(apps, schema_editor):
    table = "cms_schoolsettings"
    with connection.cursor() as cur:
        existing = {
            col.name
            for col in connection.introspection.get_table_description(cur, table)
        }
        additions = [
            (
                "admissions_academic_year",
                "ALTER TABLE cms_schoolsettings ADD COLUMN admissions_academic_year varchar(50) NOT NULL DEFAULT '2026-27'",
            ),
            (
                "admissions_close_date",
                "ALTER TABLE cms_schoolsettings ADD COLUMN admissions_close_date date NULL",
            ),
            (
                "admissions_open",
                "ALTER TABLE cms_schoolsettings ADD COLUMN admissions_open boolean NOT NULL DEFAULT true",
            ),
            (
                "admissions_start_date",
                "ALTER TABLE cms_schoolsettings ADD COLUMN admissions_start_date date NULL",
            ),
        ]
        for name, sql in additions:
            if name not in existing:
                cur.execute(sql)


def _drop_columns(apps, schema_editor):
    # Reverse: drop only the columns this migration may have added.
    with connection.cursor() as cur:
        for name in (
            "admissions_academic_year",
            "admissions_close_date",
            "admissions_open",
            "admissions_start_date",
        ):
            cur.execute(f"ALTER TABLE cms_schoolsettings DROP COLUMN IF EXISTS {name}")


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_campus_city_campus_country_campus_email_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="schoolsettings",
                    name="admissions_academic_year",
                    field=models.CharField(default="2026-27", max_length=50),
                ),
                migrations.AddField(
                    model_name="schoolsettings",
                    name="admissions_close_date",
                    field=models.DateField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="schoolsettings",
                    name="admissions_open",
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name="schoolsettings",
                    name="admissions_start_date",
                    field=models.DateField(blank=True, null=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    _add_missing_columns,
                    reverse_code=_drop_columns,
                ),
            ],
        ),
    ]
