# Generated by Django 5.2.16 on 2026-08-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_dedupe_whychoose_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(default='PDF', max_length=10)),
                ('category', models.CharField(default='Curriculum', max_length=50)),
                ('target_class_id', models.IntegerField(blank=True, null=True)),
                ('target_audience', models.CharField(blank=True, default='', max_length=200)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_name', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField(help_text='ID of the portal_class row')),
                ('academic_level', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('age_criteria', models.CharField(blank=True, default='', max_length=200)),
                ('student_teacher_ratio', models.CharField(blank=True, default='', max_length=50)),
                ('learning_objectives', models.TextField(blank=True, default='')),
                ('academic_approach', models.TextField(blank=True, default='')),
                ('facilities', models.TextField(blank=True, default='')),
                ('activities', models.TextField(blank=True, default='')),
                ('co_curricular', models.TextField(blank=True, default='')),
                ('assessment_pattern', models.TextField(blank=True, default='')),
                ('promotion_policy', models.TextField(blank=True, default='')),
                ('learning_outcomes', models.TextField(blank=True, default='')),
                ('cover_image_url', models.URLField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['class_id'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('curriculum_name', models.CharField(default='CBSE', max_length=50)),
                ('syllabus_description', models.TextField(blank=True, default='')),
                ('learning_outcomes', models.TextField(blank=True, default='')),
                ('semester_info', models.CharField(blank=True, default='', max_length=200)),
                ('topics_covered', models.TextField(blank=True, default='')),
                ('brochure_url', models.URLField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['class_id', 'curriculum_name'],
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='ID of the auth user', unique=True)),
                ('designation', models.CharField(max_length=150)),
                ('qualification_detail', models.CharField(blank=True, default='', max_length=300)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('specializations', models.CharField(blank=True, default='', max_length=500)),
                ('achievements', models.TextField(blank=True, default='')),
                ('research', models.TextField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('photo_url', models.URLField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FacultySubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
            ],
            options={
                'ordering': ['faculty_id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField(help_text='ID of the portal_subject row')),
                ('description', models.TextField(blank=True, default='')),
                ('learning_outcomes', models.TextField(blank=True, default='')),
                ('teaching_methodology', models.TextField(blank=True, default='')),
                ('activities', models.TextField(blank=True, default='')),
                ('projects', models.TextField(blank=True, default='')),
                ('assessment', models.TextField(blank=True, default='')),
                ('recommended_books', models.TextField(blank=True, default='')),
                ('cover_image_url', models.URLField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['subject_id'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_status',
            field=models.CharField(blank=True, default='', help_text='Scheduled / Completed / Cancelled', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interviewer_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='location_or_link',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.CreateModel(
            name='ClassSubjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('is_compulsory', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['class_id', 'sort_order'],
                'unique_together': {('class_id', 'subject_id')},
            },
        ),
    ]
