-- Parent portal exam extensions: revaluation + certificate requests.
-- Applied by `python manage.py apply_portal_schema` alongside the other
-- portal_extension_*.sql files (see portal/management/commands/apply_portal_schema.py).

CREATE TABLE IF NOT EXISTS public.portal_revaluation (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  result_id integer,
  subject_name varchar(150) NOT NULL DEFAULT '',
  exam_name varchar(150) NOT NULL DEFAULT '',
  reason text NOT NULL DEFAULT '',
  status varchar(30) NOT NULL DEFAULT 'Pending',
  teacher_remarks text NOT NULL DEFAULT '',
  requested_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.portal_certificate_request (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  certificate_type varchar(100) NOT NULL,
  exam_name varchar(150) NOT NULL DEFAULT '',
  status varchar(30) NOT NULL DEFAULT 'Pending',
  verification_code varchar(64) NOT NULL DEFAULT '',
  requested_at timestamptz NOT NULL DEFAULT now(),
  issued_date date
);

CREATE TABLE IF NOT EXISTS public.portal_supplementary_request (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  subject_id integer,
  subject_name varchar(150) NOT NULL DEFAULT '',
  original_exam_schedule_id integer,
  original_exam_name varchar(150) NOT NULL DEFAULT '',
  status varchar(30) NOT NULL DEFAULT 'Pending',
  grade_letter varchar(2) NOT NULL DEFAULT '',
  requested_at timestamptz NOT NULL DEFAULT now()
);
