-- ---------------------------------------------------------------------------
-- Transport module (admin portal)
--   - portal_driver, portal_attendant, portal_pickup_point, portal_transport_pass,
--     portal_transport_trip, portal_transport_alert, portal_transport_settings
--   - extends portal_route with vehicle/attendant assignments (the admin
--     Transport page saves these on routes). Live-map and reports are
--     computed on read.
-- Idempotent: safe to re-run. Tracked in portal_schema_migrations.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.portal_driver (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL UNIQUE REFERENCES public.auth_user(id) ON DELETE CASCADE,
  license_number varchar(100),
  phone varchar(30),
  vehicle_id integer REFERENCES public.portal_vehicle(id) ON DELETE SET NULL,
  is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.portal_attendant (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL UNIQUE REFERENCES public.auth_user(id) ON DELETE CASCADE,
  phone varchar(30),
  assigned_route_id integer REFERENCES public.portal_route(id) ON DELETE SET NULL,
  is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.portal_pickup_point (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_id integer NOT NULL REFERENCES public.portal_route(id) ON DELETE CASCADE,
  name varchar(200) NOT NULL,
  sequence_order integer NOT NULL DEFAULT 1,
  pickup_time time,
  drop_time time
);
CREATE INDEX IF NOT EXISTS idx_pickup_point_route ON public.portal_pickup_point(route_id, sequence_order);

ALTER TABLE public.portal_route
  ADD COLUMN IF NOT EXISTS vehicle_id integer REFERENCES public.portal_vehicle(id) ON DELETE SET NULL;
ALTER TABLE public.portal_route
  ADD COLUMN IF NOT EXISTS attendant_id integer REFERENCES public.portal_attendant(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS public.portal_transport_pass (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL UNIQUE REFERENCES public.auth_user(id) ON DELETE CASCADE,
  pass_number varchar(40) UNIQUE NOT NULL,
  issued_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.portal_transport_trip (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id integer NOT NULL REFERENCES public.portal_vehicle(id) ON DELETE CASCADE,
  route_id integer REFERENCES public.portal_route(id) ON DELETE SET NULL,
  trip_date date NOT NULL DEFAULT CURRENT_DATE,
  status varchar(30) NOT NULL DEFAULT 'Scheduled',
  started_at timestamptz,
  ended_at timestamptz,
  CHECK (status IN ('Scheduled', 'In Progress', 'Completed', 'Cancelled'))
);
CREATE INDEX IF NOT EXISTS idx_transport_trip_date ON public.portal_transport_trip(trip_date);

CREATE TABLE IF NOT EXISTS public.portal_transport_alert (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(30) NOT NULL,
  message text NOT NULL,
  vehicle_id integer REFERENCES public.portal_vehicle(id) ON DELETE SET NULL,
  route_id integer REFERENCES public.portal_route(id) ON DELETE SET NULL,
  created_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (type IN ('Bus Arrived', 'Delay Alert', 'Route Changed', 'Emergency', 'Info'))
);

CREATE TABLE IF NOT EXISTS public.portal_transport_settings (
  id integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  contact_number varchar(30),
  annual_transport_fee numeric NOT NULL DEFAULT 0,
  fee_due_date date,
  gps_update_interval_sec integer NOT NULL DEFAULT 30
);

INSERT INTO public.portal_transport_settings (id)
SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM public.portal_transport_settings WHERE id = 1);