-- ---------------------------------------------------------------------------
-- Payroll module (Admin Portal — HR / Payroll)
-- Added to close the "Payroll" / "HR" gap from the EduNova requirements doc.
-- One row per employee per pay period. monthly_salary is copied from
-- portal_employee at generation time so historical payslips don't change
-- retroactively if an employee's salary is later revised.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_payroll_record (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id integer NOT NULL REFERENCES public.portal_employee(user_id) ON DELETE CASCADE,
  pay_month date NOT NULL,                    -- always stored as the 1st of the month
  basic_salary numeric NOT NULL DEFAULT 0,
  allowances numeric NOT NULL DEFAULT 0,
  deductions numeric NOT NULL DEFAULT 0,
  net_pay numeric NOT NULL DEFAULT 0,
  status varchar(20) NOT NULL DEFAULT 'Pending',   -- Pending | Paid
  paid_on timestamptz,
  generated_by integer REFERENCES public.auth_user(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (employee_id, pay_month)
);
CREATE INDEX IF NOT EXISTS idx_payroll_month ON public.portal_payroll_record(pay_month);
CREATE INDEX IF NOT EXISTS idx_payroll_employee ON public.portal_payroll_record(employee_id);
