-- ---------------------------------------------------------------------------
-- Fee management module (admin portal)
--   - portal_academic_year, portal_fee_category, portal_fee_assignment,
--     portal_fee_concession  (fee ledger and reports are computed on read)
--   - extends portal_fee_structure with the full breakdown fields used by
--     the admin Fees page (Components of the old structure are preserved).
-- Idempotent: safe to re-run with CREATE TABLE IF NOT EXISTS / ADD COLUMN
-- IF NOT EXISTS. Tracked in portal_schema_migrations by apply_portal_schema.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.portal_academic_year (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) UNIQUE NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  is_active boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.portal_fee_category (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) UNIQUE NOT NULL,
  description text,
  sort_order integer NOT NULL DEFAULT 99,
  is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.portal_fee_assignment (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fee_structure_id integer NOT NULL
    REFERENCES public.portal_fee_structure(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (fee_structure_id, student_id)
);
CREATE INDEX IF NOT EXISTS idx_fee_assignment_structure ON public.portal_fee_assignment(fee_structure_id);

CREATE TABLE IF NOT EXISTS public.portal_fee_concession (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer NOT NULL REFERENCES public.auth_user(id) ON DELETE CASCADE,
  fee_structure_id integer NOT NULL
    REFERENCES public.portal_fee_structure(id) ON DELETE CASCADE,
  concession_type varchar(60) NOT NULL DEFAULT 'Scholarship',
  discount_amount numeric NOT NULL DEFAULT 0,
  discount_percent numeric NOT NULL DEFAULT 0,
  reason text,
  CHECK (discount_amount = 0 OR discount_percent = 0),
  CHECK (discount_percent >= 0 AND discount_percent <= 100),
  CHECK (discount_amount >= 0)
);
CREATE INDEX IF NOT EXISTS idx_fee_concession_structure ON public.portal_fee_concession(fee_structure_id);

-- Full fee-structure breakdown used by the admin Fees form. All new columns
-- are additive so existing rows keep working.
ALTER TABLE public.portal_fee_structure
  ADD COLUMN IF NOT EXISTS academic_year_id integer
    REFERENCES public.portal_academic_year(id) ON DELETE SET NULL;
ALTER TABLE public.portal_fee_structure
  ADD COLUMN IF NOT EXISTS admission_fee numeric NOT NULL DEFAULT 0;
ALTER TABLE public.portal_fee_structure
  ADD COLUMN IF NOT EXISTS library_fee numeric NOT NULL DEFAULT 0;
ALTER TABLE public.portal_fee_structure
  ADD COLUMN IF NOT EXISTS exam_fee numeric NOT NULL DEFAULT 0;
ALTER TABLE public.portal_fee_structure
  ADD COLUMN IF NOT EXISTS misc_fee numeric NOT NULL DEFAULT 0;
ALTER TABLE public.portal_fee_structure
  ADD COLUMN IF NOT EXISTS due_date date;
ALTER TABLE public.portal_fee_structure
  ADD COLUMN IF NOT EXISTS late_fine_per_day numeric NOT NULL DEFAULT 0;
ALTER TABLE public.portal_fee_structure
  ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.portal_fee_structure
  ADD COLUMN IF NOT EXISTS is_published boolean NOT NULL DEFAULT false;