import sys
import os
import django

# Setup django environment
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from django.db import connection

queries = [
    # 1. Create portal_chapter table
    """
    CREATE TABLE IF NOT EXISTS public.portal_chapter (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        course_id integer NOT NULL REFERENCES public.portal_course(id) ON DELETE CASCADE,
        title varchar(200) NOT NULL,
        description text,
        sort_order integer NOT NULL DEFAULT 0,
        created_at timestamptz DEFAULT now()
    );
    """,
    # 2. Create portal_lesson table
    """
    CREATE TABLE IF NOT EXISTS public.portal_lesson (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        chapter_id integer NOT NULL REFERENCES public.portal_chapter(id) ON DELETE CASCADE,
        title varchar(200) NOT NULL,
        description text,
        sort_order integer NOT NULL DEFAULT 0,
        created_at timestamptz DEFAULT now()
    );
    """,
    # 3. Add columns to portal_course_content
    "ALTER TABLE public.portal_course_content ADD COLUMN IF NOT EXISTS lesson_id integer REFERENCES public.portal_lesson(id) ON DELETE CASCADE;",
    "ALTER TABLE public.portal_course_content ADD COLUMN IF NOT EXISTS description text;",
    "ALTER TABLE public.portal_course_content ADD COLUMN IF NOT EXISTS due_date timestamptz;",
    "ALTER TABLE public.portal_course_content ADD COLUMN IF NOT EXISTS max_marks integer;",
    "ALTER TABLE public.portal_course_content ADD COLUMN IF NOT EXISTS quiz_id integer REFERENCES public.portal_quiz(id) ON DELETE SET NULL;",
    "ALTER TABLE public.portal_course_content ADD COLUMN IF NOT EXISTS assignment_id integer REFERENCES public.portal_assignment(id) ON DELETE SET NULL;",
    "ALTER TABLE public.portal_course_content ADD COLUMN IF NOT EXISTS visible_from timestamptz DEFAULT now();",
    "ALTER TABLE public.portal_course_content ADD COLUMN IF NOT EXISTS uploaded_at timestamptz DEFAULT now();",
    "ALTER TABLE public.portal_course_content ADD COLUMN IF NOT EXISTS download_count integer DEFAULT 0;"
]

print("Starting LMS Database migration...")
with connection.cursor() as cursor:
    for q in queries:
        try:
            cursor.execute(q)
            print(f"Success: {q.strip().splitlines()[0][:60]}...")
        except Exception as e:
            print(f"Error executing: {q.strip().splitlines()[0][:60]}... => {e}")

print("Migration completed.")
