"""Add the full admissions schema.

The live Supabase table `admissions_admissionenquiry` was created by an older,
richer schema (and migrations were faked in), so it already contains most of
these columns — but the Django model did not declare them, which made every
public admission INSERT fail with a NotNullViolation. This migration syncs the
model state to the full schema and, with ADD COLUMN IF NOT EXISTS, is safe to
run against BOTH a fresh database (where the columns must be created) and the
existing production database (where they already exist and are left untouched).

Generated by hand (not makemigrations) because the production table pre-exists.
"""
from django.db import migrations, models


# Every column the model now declares that migration 0001/0002/0003 don't know.
# Each entry: (field name, Django model field, raw SQL column definition).
NEW_FIELDS = [
    # Demographics
    ("blood_group", models.CharField(blank=True, default="", max_length=10), "varchar(10) NOT NULL DEFAULT ''"),
    ("aadhaar_number", models.CharField(blank=True, default="", max_length=20), "varchar(20) NOT NULL DEFAULT ''"),
    ("nationality", models.CharField(blank=True, default="Indian", max_length=50), "varchar(50) NOT NULL DEFAULT 'Indian'"),
    ("religion", models.CharField(blank=True, default="", max_length=50), "varchar(50) NOT NULL DEFAULT ''"),
    ("category", models.CharField(blank=True, default="General", max_length=50), "varchar(50) NOT NULL DEFAULT 'General'"),
    ("city", models.CharField(blank=True, default="", max_length=100), "varchar(100) NOT NULL DEFAULT ''"),
    ("state", models.CharField(blank=True, default="", max_length=100), "varchar(100) NOT NULL DEFAULT ''"),
    ("country", models.CharField(blank=True, default="India", max_length=100), "varchar(100) NOT NULL DEFAULT 'India'"),
    ("pincode", models.CharField(blank=True, default="", max_length=10), "varchar(10) NOT NULL DEFAULT ''"),
    # Family / guardians
    ("father_name", models.CharField(blank=True, default="", max_length=150), "varchar(150) NOT NULL DEFAULT ''"),
    ("father_occupation", models.CharField(blank=True, default="", max_length=100), "varchar(100) NOT NULL DEFAULT ''"),
    ("father_company", models.CharField(blank=True, default="", max_length=150), "varchar(150) NOT NULL DEFAULT ''"),
    ("father_income", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True), "numeric(12,2) NULL"),
    ("father_phone", models.CharField(blank=True, default="", max_length=20), "varchar(20) NOT NULL DEFAULT ''"),
    ("father_email", models.CharField(blank=True, default="", max_length=150), "varchar(150) NOT NULL DEFAULT ''"),
    ("mother_name", models.CharField(blank=True, default="", max_length=150), "varchar(150) NOT NULL DEFAULT ''"),
    ("mother_occupation", models.CharField(blank=True, default="", max_length=100), "varchar(100) NOT NULL DEFAULT ''"),
    ("mother_company", models.CharField(blank=True, default="", max_length=150), "varchar(150) NOT NULL DEFAULT ''"),
    ("mother_phone", models.CharField(blank=True, default="", max_length=20), "varchar(20) NOT NULL DEFAULT ''"),
    ("mother_email", models.CharField(blank=True, default="", max_length=150), "varchar(150) NOT NULL DEFAULT ''"),
    ("guardian_name", models.CharField(blank=True, default="", max_length=150), "varchar(150) NOT NULL DEFAULT ''"),
    ("guardian_relationship", models.CharField(blank=True, default="", max_length=50), "varchar(50) NOT NULL DEFAULT ''"),
    ("guardian_phone", models.CharField(blank=True, default="", max_length=20), "varchar(20) NOT NULL DEFAULT ''"),
    ("guardian_address", models.TextField(blank=True, default=""), "text NOT NULL DEFAULT ''"),
    ("emergency_contact_name", models.CharField(blank=True, default="", max_length=150), "varchar(150) NOT NULL DEFAULT ''"),
    ("emergency_contact_phone", models.CharField(blank=True, default="", max_length=20), "varchar(20) NOT NULL DEFAULT ''"),
    ("emergency_contact_relation", models.CharField(blank=True, default="", max_length=50), "varchar(50) NOT NULL DEFAULT ''"),
    # Addresses
    ("permanent_address", models.TextField(blank=True, default=""), "text NOT NULL DEFAULT ''"),
    ("communication_address", models.TextField(blank=True, default=""), "text NOT NULL DEFAULT ''"),
    # Previous school
    ("prev_school_name", models.CharField(blank=True, default="", max_length=200), "varchar(200) NOT NULL DEFAULT ''"),
    ("board", models.CharField(blank=True, default="", max_length=50), "varchar(50) NOT NULL DEFAULT ''"),
    ("prev_school_grade", models.CharField(blank=True, default="", max_length=20), "varchar(20) NOT NULL DEFAULT ''"),
    ("percentage", models.CharField(blank=True, default="", max_length=20), "varchar(20) NOT NULL DEFAULT ''"),
    ("reason_for_leaving", models.TextField(blank=True, default=""), "text NOT NULL DEFAULT ''"),
    # Enquiry / preference
    ("source_of_enquiry", models.CharField(blank=True, default="Website", max_length=100), "varchar(100) NOT NULL DEFAULT 'Website'"),
    ("preferred_branch", models.CharField(blank=True, default="", max_length=100), "varchar(100) NOT NULL DEFAULT ''"),
    ("curriculum", models.CharField(blank=True, default="CBSE", max_length=50), "varchar(50) NOT NULL DEFAULT 'CBSE'"),
    # Medical
    ("has_medical_conditions", models.BooleanField(default=False), "boolean NOT NULL DEFAULT false"),
    ("medical_details", models.TextField(blank=True, default=""), "text NOT NULL DEFAULT ''"),
    ("allergies", models.TextField(blank=True, default=""), "text NOT NULL DEFAULT ''"),
    # Documents
    ("doc_aadhaar_card", models.FileField(blank=True, null=True, upload_to="admissions/documents/"), "varchar(100) NULL"),
    ("doc_address_proof", models.FileField(blank=True, null=True, upload_to="admissions/documents/"), "varchar(100) NULL"),
    ("doc_birth_certificate", models.FileField(blank=True, null=True, upload_to="admissions/documents/"), "varchar(100) NULL"),
    ("doc_parent_id", models.FileField(blank=True, null=True, upload_to="admissions/documents/"), "varchar(100) NULL"),
    ("doc_passport_photo", models.FileField(blank=True, null=True, upload_to="admissions/documents/"), "varchar(100) NULL"),
    ("doc_previous_marks", models.FileField(blank=True, null=True, upload_to="admissions/documents/"), "varchar(100) NULL"),
    ("doc_transfer_certificate", models.FileField(blank=True, null=True, upload_to="admissions/documents/"), "varchar(100) NULL"),
    # Admin workflow pipeline
    ("allocated_class", models.CharField(blank=True, default="", max_length=200), "varchar(200) NOT NULL DEFAULT ''"),
    ("allocated_section", models.CharField(blank=True, default="", max_length=200), "varchar(200) NOT NULL DEFAULT ''"),
    ("counselling_date", models.DateTimeField(blank=True, null=True), "timestamptz NULL"),
    ("counselling_notes", models.TextField(blank=True, default=""), "text NOT NULL DEFAULT ''"),
    ("counselling_status", models.CharField(blank=True, default="", max_length=50), "varchar(50) NOT NULL DEFAULT ''"),
    ("counsellor_id", models.IntegerField(blank=True, null=True), "integer NULL"),
    ("eligibility_notes", models.TextField(blank=True, default=""), "text NOT NULL DEFAULT ''"),
    ("is_eligible", models.BooleanField(default=False), "boolean NOT NULL DEFAULT false"),
    ("is_waitlisted", models.BooleanField(default=False), "boolean NOT NULL DEFAULT false"),
    ("waitlist_position", models.IntegerField(blank=True, null=True), "integer NULL"),
    ("seat_allocated", models.BooleanField(default=False), "boolean NOT NULL DEFAULT false"),
    ("interview_date", models.DateTimeField(blank=True, null=True), "timestamptz NULL"),
    ("interview_required", models.BooleanField(default=False), "boolean NOT NULL DEFAULT false"),
    ("interview_scheduled", models.BooleanField(default=False), "boolean NOT NULL DEFAULT false"),
    ("interview_result", models.CharField(blank=True, default="", max_length=50), "varchar(50) NOT NULL DEFAULT ''"),
    ("fee_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12), "numeric(12,2) NOT NULL DEFAULT 0"),
    ("net_fee", models.DecimalField(decimal_places=2, default=0, max_digits=12), "numeric(12,2) NOT NULL DEFAULT 0"),
    ("fee_paid", models.BooleanField(default=False), "boolean NOT NULL DEFAULT false"),
    ("fee_transaction_id", models.CharField(blank=True, default="", max_length=100), "varchar(100) NOT NULL DEFAULT ''"),
    ("scholarship_discount", models.DecimalField(decimal_places=2, default=0, max_digits=12), "numeric(12,2) NOT NULL DEFAULT 0"),
    ("student_admission_number", models.CharField(blank=True, default="", max_length=50), "varchar(50) NOT NULL DEFAULT ''"),
    ("student_roll_number", models.CharField(blank=True, default="", max_length=50), "varchar(50) NOT NULL DEFAULT ''"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0003_alter_admissionenquiry_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="admissionenquiry",
                    name=name,
                    field=field,
                )
                for name, field, _sql in NEW_FIELDS
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="\n".join(
                        "ALTER TABLE admissions_admissionenquiry ADD COLUMN IF NOT EXISTS "
                        f"{name} {sql_type};"
                        for name, _field, sql_type in NEW_FIELDS
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
