# Generated by Django 5.2.16 on 2026-08-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_admissionenquiry_full_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionenquiry',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='reviewed_by',
            field=models.CharField(blank=True, default='', help_text='Admin username/name', max_length=150),
        ),
    ]
