# Generated by Django 5.2.16 on 2026-08-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_alter_admissionenquiry_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionenquiry',
            name='house',
            field=models.CharField(blank=True, default='', help_text='House (Red/Blue/Green/Yellow) for academic allocation', max_length=50),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='status',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Registered', 'Registered'), ('Counselling_Pending', 'Counselling_Pending'), ('Counselling_Done', 'Counselling_Done'), ('Verification', 'Verification'), ('Eligibility_Check', 'Eligibility_Check'), ('Screening', 'Screening'), ('Interview_Pending', 'Interview_Pending'), ('Interview_Done', 'Interview_Done'), ('Seat_Available', 'Seat_Available'), ('Seat_Waitlisted', 'Seat_Waitlisted'), ('Fee_Pending', 'Fee_Pending'), ('Approved', 'Approved'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Registered', max_length=20),
        ),
    ]
