# Generated by Django 5.2.16 on 2026-08-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_admissionenquiry_house_alter_admissionenquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionenquiry',
            name='module_allocations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
